### ISSUE TITLE
♻️ Reorganize Zod schemas

### ISSUE THREAD

**Issue by fell-lucas** [extensionly-gh/svelte-frontend#22]
Structure suggestions:
- Separate in 3 folders, one for schemas used in the client, another for the server and one for shared schemas
  - Probably not ideal because there would be many shared schemas
- One schema file to rule them all
  - Might be good enough for now but can become a huge mess when the project grows
- Create a `_schemas.ts` file for each route and put it in the route's folder
  - Duplicate schemas 
- Save only base schemas in a `schemas/index.ts` file
  - Save router-related schemas together with their query/mutation (will be neat after #19 
  - Following the same logic, save form-related schemas together with the client code. We can use different `<script>` tags for this too

**Comment by IgorDalepiane** [comment]
I think that we can put all schemas (router-related and client-related) on the related query/mutation file as in #19
